services:
  - type: web
    name: whatsapp-md-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OWNER_NUMBERS
        sync: false
      - key: PREFIX
        value: "."
      - key: BOT_NAME
        value: MD-Bot
      - key: NODE_VERSION
        value: 20.11.0
